image: tmaier/docker-compose:18

services:
  - docker:dind

stages:
  - build
  - test
  - test-installer
  - package

before_script:
  - apk add --no-cache bash make git

build:
  stage: build
  script:
    - ./build.sh
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.zip
      - dist/*.rb
      - dist/*.deb
      - dist/*.rpm
      - dist/*.txt
      - dist/linux_amd64/summon  # for test-acceptance job

test-unit:
  stage: test
  script:
    - ./test.sh
  artifacts:
    paths:
      - output/junit.xml
test-acceptance:
  stage: test
  dependencies:
    - build
  script:
    - cp ./dist/linux_amd64/summon summon
    - cd acceptance && make
test-installer-ubuntu1404:
  stage: test
  script:
    - bin/installer-test --ubuntu-14.04
test-installer-ubuntu1604:
  stage: test
  script:
    - bin/installer-test --ubuntu-16.04

